"""Add a 'is_active' property

Revision ID: 11412b845a95
Revises: 4a60a25ab994
Create Date: 2024-12-29 22:05:36.608713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11412b845a95'
down_revision = '4a60a25ab994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
