"""Add external_id to customer moderl for importing by id

Revision ID: 2b84e8876d0f
Revises: 6edc46cf98ff
Create Date: 2025-04-12 15:58:08.584239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b84e8876d0f'
down_revision = '6edc46cf98ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_external_id'))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
