"""Add groups field for customer

Revision ID: 3d2a3c1b8337
Revises: e2018a1c237e
Create Date: 2024-12-29 21:42:23.739621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2a3c1b8337'
down_revision = 'e2018a1c237e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('groups')

    # ### end Alembic commands ###
