"""Add missing field, refactor timestamps

Revision ID: 456024af7d9f
Revises: 442eb766e08c
Create Date: 2024-12-24 15:30:52.561487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456024af7d9f'
down_revision = '442eb766e08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
