"""modifications to RenatlHistory

Revision ID: 4621b5848edf
Revises: 
Create Date: 2025-03-15 16:14:37.217073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4621b5848edf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_history', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('update_type')

    # ### end Alembic commands ###
