"""Added is_available to Instrument

Revision ID: 467bb4f75801
Revises: c6093b790bc3
Create Date: 2023-08-27 15:07:20.162166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467bb4f75801'
down_revision = 'c6093b790bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
