"""modify history class

Revision ID: 69073c1c30bd
Revises: 4b0d137b00a0
Create Date: 2023-05-01 17:21:45.642580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69073c1c30bd'
down_revision = '4b0d137b00a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rental_note', sa.Text(), nullable=True))
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'instrument', ['instrument_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('rental_note')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('instrument_name')

    # ### end Alembic commands ###
