"""put customer name as dynamic display name

Revision ID: 90decce17172
Revises: 456024af7d9f
Create Date: 2024-12-24 15:40:42.606165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90decce17172'
down_revision = '456024af7d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
